./multifitpol.sh -n nTnew thio_1T_neut_fit_aniso thio_2T_neut_fit_aniso thio_3T_neut_fit_aniso thio_4T_neut_fit_aniso thio_5T_neut_fit_aniso thio_6T_neut_fit_aniso thio_7T_neut_fit_aniso thio_8T_neut_fit_aniso

./multifitpol.sh -n nTs_acenes_picen thio_1T_neut_fit_aniso thio_2T_neut_fit_aniso thio_3T_neut_fit_aniso thio_4T_neut_fit_aniso thio_5T_neut_fit_aniso thio_6T_neut_fit_aniso thio_7T_neut_fit_aniso thio_8T_neut_fit_aniso BENZENE_picen_fit_aniso NAPHTA_picen_fit_aniso TETCEN_picen_fit_aniso ANTCEN_picen_fit_aniso Pc_picen_fit_aniso

./multifitpol.sh -n nTs_acenes_singcen thio_1T_neut_fit_aniso thio_2T_neut_fit_aniso thio_3T_neut_fit_aniso thio_4T_neut_fit_aniso thio_5T_neut_fit_aniso thio_6T_neut_fit_aniso thio_7T_neut_fit_aniso thio_8T_neut_fit_aniso BENZENE_singcen_fit_aniso NAPHTA_singcen_fit_aniso TETCEN_singcen_fit_aniso ANTCEN_singcen_fit_aniso Pc_singcen_fit_aniso

./multifitpol.sh -n acenes_picen BENZENE_picen_fit_aniso NAPHTA_picen_fit_aniso TETCEN_picen_fit_aniso ANTCEN_picen_fit_aniso Pc_picen_fit_aniso

./multifitpol.sh -n acenes_singcen BENZENE_singcen_fit_aniso NAPHTA_singcen_fit_aniso TETCEN_singcen_fit_aniso ANTCEN_singcen_fit_aniso Pc_singcen_fit_aniso
